Mysql:
  UserCode: root
  Password: password
  DBName: "yh2"
  Url: "tcp(192.168.0.201:3306)/{db}?charset=utf8"

  ShowSQL: true
  UserCache: false
  MaxIdleConnS: 10
  MaxOpenConnS: 100
  ConnMaxLifetime: 60
Influx:
  HttpConf:
    Addr: "http://192.168.0.203:9086"
    Username: ""
    Password: ""
    UserAgent: ""
    Timeout: 0
    InsecureSkipVerify: false
  GetTimeout: 3000000000
  MinOpen: 20
  MaxOpen: 10000

Redis:
  #"localhost:6379",
  Addr: "192.168.0.201:6379"
  Password: ""

#初始化默认服务配置,存储在mariaDB数据库中
ServicesAddrList:
  - Emq:
      Host: "192.168.0.201"
      TCPPort: "1883"
      WSPort: "8083"
    Redis: "192.168.0.201:6379"
    Influx: "http://192.168.0.201:9086"
  - Emq:
      Host: "192.168.0.202"
      TCPPort: "1883"
      WSPort: "8083"
    Redis: "192.168.0.202:6379"
    Influx: "http://192.168.0.202:9086"
  - Emq:
      Host: "192.168.0.203"
      TCPPort: "1883"
      WSPort: "8083"
    Redis: "192.168.0.203:6379"
    Influx: "http://192.168.0.203:9086"